<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\PharmaVault.Data\PharmaVault.Data.csproj" />
    <ProjectReference Include="..\PharmaVault.Core\PharmaVault.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>af9c8260-8785-4024-a11d-dd371c19bd02</UserSecretsId>
  </PropertyGroup>

</Project>
